### ISSUE TITLE
Basic failover CLI extension

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd-failover#69]
Write a `linkerd-failover` CLI that will work as an extension.

It should support a few simple commands:

* `linkerd failover install` should initially just print a message detailing how to use helm installation and fail. Similarly for `linkerd failover uninstall`
* `linkerd failover check -o json` should print messages JSON-formatted check statuses so that `linkerd check` can include the failover extension. It should validate that the failover controller pod is running.
* Supporting `linkerd failover check` with pretty output is optional. It would be fine for it to print an error directing users to use `linkerd check` as a first version (because, for instance, we really need SMI checks to run to check failover health).

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd-failover/pull/84
